### ISSUE TITLE
Copy entire folders not just specific files.

### ISSUE THREAD

**Issue by pokeyjojo** [Fernthedev/desktop_adb_file_browser#10]
Is there any way to copy entire folders? or somehow compress a folder into a zip file? and download that? I don't see any way to do that in the current build

**Comment by Fernthedev** [comment]
Have you tried the latest action build? You should be able to right click and download a folder 
![image](https://github.com/Fernthedev/desktop_adb_file_browser/assets/15272073/576b973c-870f-4a3a-ac4a-398fb22933be)

**Comment by Fernthedev** [comment]
Tested this and it seems to work, closing for now. Feel free to reopen if this is not resolved
