### ISSUE TITLE
The File Browser cannot be accessed when 2 devices are connected

### ISSUE THREAD

**Issue by ShlomoCode** [Fernthedev/desktop_adb_file_browser#20]
I choose one of the devices:
![CleanShot 2024-09-02 at 01 43 19@2x](https://github.com/user-attachments/assets/f0509885-d0d3-4f84-8d74-ed6cd8970009)
But when I go to the file browser tab I get an adb "more than one device emulator" error:
![CleanShot 2024-09-02 at 01 43 23@2x](https://github.com/user-attachments/assets/467b62a4-66af-4520-8890-8d8f939b5440)

**Comment by Fernthedev** [comment]
Hi, could you share your logs from `%appdata%\com.github.Fernthedev\deskto_adb_file_browser\logs`? Do be aware this can expose file and directory names

**Comment by ShlomoCode** [comment]
The path you mentioned is for Windows, I'm using a Mac. What is the log path on MacOS?

**Comment by ShlomoCode** [comment]
[20240902_015654.log](https://github.com/user-attachments/files/16830739/20240902_015654.log)

**Comment by Fernthedev** [comment]
Hi, I was unable to reproduce your issue. Can you try with this build? 
https://github.com/Fernthedev/desktop_adb_file_browser/actions/runs/10022060214/artifacts/1722117012

**Comment by ShlomoCode** [comment]
Thanks, it does work. Can you include an update option in the app?

**Comment by Fernthedev** [comment]
No update mechanism for the moment, it's complicated to implement. Glad to see it resolved though, [I released a new version here.](https://github.com/Fernthedev/desktop_adb_file_browser/releases/tag/v1.4.0)

**Comment by ShlomoCode** [comment]
If you add an option to install the app using package managers (for MacOS it's a homebrew formula) they will be able to handle updates automatically.
