### ISSUE TITLE
Update README for users unfamiliar with Flutter

### ISSUE THREAD

**Issue by dandv** [Fernthedev/desktop_adb_file_browser#6]
How do I run this thing :)

**Comment by Fernthedev** [comment]
You're right, the README has been left untouched for a while. 

You can run this by checking the actions tab for CI prebuilt artifacts or the releases tab for prebuilt binaries as well.

There's Linux, Mac and Windows support, though I admit the UI is jarring for a desktop app. I welcome any contributions to the design of it.
